on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
    - name: Hello world action step
      id: hello
      uses: shyd/action-delete-release@v2
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        release_tag: tdevelop-ongoing
        
    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        overwrite: true
        prerelease: true
        tag: develop-ongoing
        body: "Built from commit: ${{ github.sha }}"
