on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
    - name: Hello world action step
      id: hello
      uses: shyd/action-delete-release@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        release_tag: main
        
    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: README.md
        prerelease: true
        asset_name: wj200_modbus_comm.armhf.tar.gz
        #tag: develop-ongoing
        tag: ${{ github.ref }}
        body: "Built from commit: ${{ github.sha }}"
